### PR TITLE
Add building debian package.

### PR DESCRIPTION
**Pull request by agustinhenze**
The package is builded with /usr/local prefix and all projects must be support make DESTDIR=PATH_DEST.

### CODE REVIEW

**Comment by chrysn** [comment]
i've created a different solution before i saw your approach.

my approach[0] doesn't modify the existing summon-arm-toolchain (except for a patch i hope to be accepted concerning DESTDIR), but creates a debian/ directory in there and lets the usual debian tools run the package creation process.

it doesnt build openocd, as that's packaged in debian anyway. i'd like to not build binutils as well, as we could depend on binutils-multiarch, but i'd probably have to tell a bunch of tools to use `objdump` instead of `arm-none-eabi-objdump` etc.

[0] https://github.com/chrysn/summon-arm-toolchain

**Comment by esden** [comment]
hi @agustinhenze thanks for the pull request. What is your take on @chrysn comment? Also the darwin/BSD version of sed does not have the -r option.

What is the general take on this. Should we have integrated debian build in SAT at all?

**Comment by agustinhenze** [comment]
Hi @esden and @chrysn sorry for my delay. About the approach of @chrysn, is a quite simple therefore it's good.
But I think my approach is more flexible without adding much complexity e.g. build different debian packages with all arguments accepted for sat script.

May be we need split the script into "modules" (different files) for readability, and then for add support to debian packaging would only add the include statement...

About sed -r, I'll fix it right now.

**Comment by chrysn** [comment]
the main reason i'm disabling more and more components is that i consider whatever deb is built from summon-arm-toolchain to be transitional; i mainly use them as a path to packaging the other components involved. (in the long run, sat shouldn't be run on debian / derivatives as there'll be packages for everything involved).

a modular approach might server both the sat script and its packaging efforts well -- as long as its complexity doesn't grow to the point where it becomes a package management system by itself. (actually it does pretty much the same things a debian package usually does -- unpack, apply patches, build with preset parameters).

**Comment by esden** [comment]
Heya sorry for the super long lead time for me to respond or do actually anything on summon-arm-toolchain. I now updated and merged all the stuff I could think of including all the other pull requests. The beta branch is now also merged into master. This pull request is rather big compared to others so please let me know if there is anything in here that still needs to go into sat. If possible please create a pull request ontop of beta branch so we can give it a spin before it becomes "stable" (master branch)

**Comment by esden** [comment]
I interpret the silence as "everything is in what should be in and this pull request is now obsolete" :D ... Closing ^^

**Pull request closed without merging**
