### PR TITLE
Updating all softwares' versions

### PR DESCRIPTION
**Pull request by pedrovanzella**

### CODE REVIEW

**Comment by pedrovanzella** [comment]
hold on, there are a few bugs to squash on this and a patch to rewrite.

**Comment by esden** [comment]
Hi thanks for the pull request. Sadly the multilib support patch to linaro gcc does not apply any more with your patch. :(

```
******************************************************************
* Patching gcc to add multilib support
******************************************************************
patching file gcc/config/arm/t-arm-elf
Hunk #1 FAILED at 31.
1 out of 1 hunk FAILED -- saving rejects to file gcc/config/arm/t-arm-elf.rej
```

Also please base your patches ontop of the beta branch from now on. This is the testing branch for updates and improvements of SAT.

Thanks again for the pull request. I hope we can merge it into beta branch soon! :)

**Comment by mpfleger** [comment]
Hi guys.

Firstly I'd like to thank you all for some superb work on this!

OK - so I've just had a run-in with the cluebat. I see now what the pull request that pedrovanzella did was all about. I've essentially been replicating his work... lol.

So what I'm back to asking is about building this on Fedora, given your comments on the linaro gcc multilib issue. For those of us who are a bit less experienced with these things... could you please elaborate on what exactly has broken, there?

TIA,
M

**Comment by esden** [comment]
merged beta branch with updated packages and patches. Should make this pull request obsolete. Thanks for sending it over though. Please send pull requests to the beta branch in the future. :)

**Pull request closed without merging**
